### ISSUE TITLE
IOS全屏不行

### ISSUE THREAD

**Issue by micaiyuyu** [post-programming/videojs-landscape-fullscreen#19]
IOS全屏不生效，如何解决

**Comment by prateekrastogi** [comment]
Sorry, was busy fixing fate of China and xinhuanet.com in NewsReel Programming. Realized since lazy American Bastards in California are getting $1500 per week, i.e. $78k yearly, unemployment benefits/UBI. 

`China and its Yuan future` will always be "sick man of Europe" with glitzy ambitions due to said dollars perforate. 

As far as iOS is concerned,  kindly update your device with latest iOS as per as Apple's legal policies.
